### ISSUE TITLE
TODO before launch

### ISSUE THREAD

**Issue by granawkins** [granawkins/latent-dictionary#9]
- [x] SSL
- [x] User tokens: generate on backend, keep in window, throttle
- [ ] Captcha: if throttle limit hits, require captcha before doing anything else
- [x] Favicon
- [x] Google Analytics
- [x] Log activity/stats/searches, expose somewhere
- [x] Add a license to the repo
- [x] Fill-in README
